export type ItemGroup = {
  name: string;
  items: string[];
};

export const ITEM_GROUPS = [
  {
    name: "Equipment",
    items: [
      "Canvas",
      "Space Credits",
      "Zone Chip",
      "Powerkit",
      "Medkit",
      "Anti-Radiation MedKit",
      "Clang Cola",
      "Cosmic Coffee",
      "S-10 Magazine",
      "S-10E Magazine",
      "S-20A Magazine",
      "MR-20 Magazine",
      "MR-8P Magazine",
      "MR-50A Magazine",
      "MR-30E Magazine",
      "Gatling Ammo Box",
      "Rocket",
      "Autocannon Magazine",
      "Artillery Shell",
      "Assault Cannon Shell",
      "Large Railgun Sabot",
      "Small Railgun Sabot",
      "Flare Gun Clip",
      "Fireworks Box",
    ],
  },
  {
    name: "Components",
    items: [
      "Bulletproof Glass",
      "Computer",
      "Construction Comp.",
      "Detector Components",
      "Display",
      "Explosives",
      "Girder",
      "Gravity Comp.",
      "Interior Plate",
      "Medical Components",
      "Metal Grid",
      "Motor",
      "Power Cell",
      "Radio-comm Comp.",
      "Reactor Comp.",
      "Solar Cell",
      "Steel Plate",
      "Steel Tube, Large",
      "Steel Tube, Small",
      "Superconductor",
      "Thruster Components",
      "Engineer Plushie",
      "Saberoid Plushie",
    ],
  },
  {
    name: "Prototech Components",
    items: [
      "Prototech Frame",
      "Prototech Cooling Unit",
      "Prototech Circuitry",
      "Prototech Machinery",
      "Prototech Propulsion Unit",
      "Prototech Capacitor",
      "Prototech Panel",
    ],
  },
  {
    name: "Materials",
    items: [
      "Cobalt Ingot",
      "Gold Ingot",
      "Gravel",
      "Iron Ingot",
      "Magnesium Powder",
      "Nickel Ingot",
      "Platinum Ingot",
      "Silicon Wafer",
      "Silver Ingot",
      "Uranium Ingot",
    ],
  },
  {
    name: "Ores",
    items: [
      "Iron Ore",
      "Silicon Ore",
      "Nickel Ore",
      "Cobalt Ore",
      "Magnesium Ore",
      "Silver Ore",
      "Gold Ore",
      "Platinum Ore",
      "Uranium Ore",
      "Ice",
      "Stone",
      "Scrap Metal",
      "Prototech Scrap",
    ],
  },
  {
    name: "Ingredients",
    items: [
      "Fruits",
      "Grains",
      "Mushrooms",
      "Vegetables",
      "Algae",
      "Mammal Meat (Raw)",
      "Mammal Meat (Cooked)",
      "Insect Meat (Raw)",
      "Insect Meat (Cooked)",
    ],
  },
  {
    name: "Seeds",
    items: [
      "Fruit Seeds",
      "Grain Seeds",
      "Mushroom Spores",
      "Vegetable Seeds",
    ],
  },
  {
    name: "Food",
    items: [
      "Meal Pack (Kelp Crisp)",
      "Meal Pack (Fruit Bar)",
      "Meal Pack (Garden Slaw)",
      "Meal Pack (Red Pellets)",
      "Meal Pack (Chili)",
      "Meal Pack (Ramen)",
      "Meal Pack (Flatbread)",
      "Meal Pack (Fruit Pastry)",
      "Meal Pack (Veggie Burger)",
      "Meal Pack (Green Pellets)",
      "Meal Pack (Curry)",
      "Meal Pack (Dumplings)",
      "Meal Pack (Spaghetti)",
      "Meal Pack (Lasagna)",
      "Meal Pack (Burrito)",
      "Meal Pack (Frontier Stew)",
      "Meal Pack (Seared Sabiroid)",
      "Meal Pack (Steak Dinner)",
    ],
  },
] as const satisfies ItemGroup[];

export const ITEM_NAMES = ITEM_GROUPS.flatMap((group) => group.items);
